name: Tests with Vitest and PHPUnit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: psr
          mysql root password: root123
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Captura diretório do pnpm
        id: pnpm-cache
        run: echo "dir=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"
      - name: Captura diretório do composer
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"
      - name: Cache
        id: cache-npm-php
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.dir }}
            ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-cache-${{ hashFiles('**/composer.lock') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-cache-
      - name: Instala as dependências do composer
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Gera uma key aleatória
        run: php artisan key:generate
      - name: Permissão de diretório
        run: chmod -R 777 storage bootstrap/cache
      - name: Instala as dependências JS
        run: pnpm i
      - name: Vite Build
        run: pnpm build
      - name: Executa testes com o PHP
        env:
          DB_DATABASE: psr
          DB_PASSWORD: root123
        run: |
          php artisan serve --host localhost &
          php artisan migrate
          php artisan db:seed
          php artisan test

  js-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Captura diretório do pnpm
        id: pnpm-cache
        run: echo "dir=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"
      - name: Cache
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.dir }}
          key: ${{ runner.os }}-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-cache-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Lista módulos do npm
        continue-on-error: true
        run: npm list
      - name: Instala dependências do JS
        run: pnpm i
      - name: Vite Build
        run: pnpm build
      - name: Executa testes como vitest
        run: npx vitest
